# Generated by Django 3.0.8 on 2020-07-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_stockfoliouser_stockportfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockfoliouser',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='stockfoliouser',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
