# Generated by Django 3.0.8 on 2020-07-30 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trading', '0003_auto_20200730_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockfoliouser',
            name='user',
        ),
        migrations.AddField(
            model_name='stockfoliouser',
            name='owner',
            field=models.ForeignKey(default='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
